src/Entity/Follow.php
<?php

namespace App\Entity;

use App\Repository\FollowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FollowRepository::class)]
class Follow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'follows')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $UserID = null;

    #[ORM\ManyToOne(inversedBy: 'follows')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $FollowerID = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }

    public function getFollowerID(): ?Utilisateur
    {
        return $this->FollowerID;
    }

    public function setFollowerID(?Utilisateur $FollowerID): static
    {
        $this->FollowerID = $FollowerID;

        return $this;
    }
}

src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateTime = null;



    #[ORM\ManyToOne(inversedBy: 'publications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $UserID = null;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'PostID', cascade: ["remove"])]
    private Collection $commentaires;

    #[ORM\Column(length: 255)]
    private ?string $Post_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Post_content = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'publication')]
    private Collection $likes;


    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostID(): ?int
    {
        return $this->PostID;
    }

    public function setPostID(int $PostID): static
    {
        $this->PostID = $PostID;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): static
    {
        $this->DateTime = $DateTime;

        return $this;
    }


    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }


    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setPostID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPostID() === $this) {
                $commentaire->setPostID(null);
            }
        }

        return $this;
    }

    public function getPostType(): ?string
    {
        return $this->Post_type;
    }

    public function setPostType(string $Post_type): static
    {
        $this->Post_type = $Post_type;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->Post_content;
    }

    public function setPostContent(?string $Post_content): static
    {
        $this->Post_content = $Post_content;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setPublication($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPublication() === $this) {
                $like->setPublication(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this Email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Username = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $Password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfilePicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfileCover = null;

    #[ORM\OneToMany(targetEntity: Connexion::class, mappedBy: 'UserID')]
    private Collection $connexions;

    #[ORM\OneToMany(targetEntity: Publication::class, mappedBy: 'UserID')]
    private Collection $publications;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'UserID')]
    private Collection $commentaires;

    #[ORM\OneToMany(targetEntity: Follow::class, mappedBy: 'UserID')]
    private Collection $follows;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Bio = null;

    #[ORM\Column(nullable: true)]
    private ?int $EcoScore = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'user')]
    private Collection $likes;

    #[ORM\Column(type: 'json')]
    private array $roles = [];
    
    public function __construct()
    {
        $this->connexions = new ArrayCollection();
        $this->publications = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->follows = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->Email; // Ou toute autre propriété qui représente l'identifiant de l'utilisateur
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): static
    {
        $this->Username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): static
    {
        $this->Password = $Password;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->ProfilePicture;
    }

    public function setProfilePicture(?string $ProfilePicture): static
    {
        $this->ProfilePicture = $ProfilePicture;

        return $this;
    }

    public function getProfileCover(): ?string
    {
        return $this->ProfileCover;
    }

    public function setProfileCover(?string $ProfileCover): static
    {
        $this->ProfileCover = $ProfileCover;

        return $this;
    }

    public function getConnexions(): Collection
    {
        return $this->connexions;
    }

    public function addConnexion(Connexion $connexion): static
    {
        if (!$this->connexions->contains($connexion)) {
            $this->connexions->add($connexion);
            $connexion->setUserID($this);
        }

        return $this;
    }

    public function removeConnexion(Connexion $connexion): static
    {
        if ($this->connexions->removeElement($connexion)) {
            if ($connexion->getUserID() === $this) {
                $connexion->setUserID(null);
            }
        }

        return $this;
    }

    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): static
    {
        if (!$this->publications->contains($publication)) {
            $this->publications->add($publication);
            $publication->setUserID($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): static
    {
        if ($this->publications->removeElement($publication)) {
            if ($publication->getUserID() === $this) {
                $publication->setUserID(null);
            }
        }

        return $this;
    }

    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUserID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            if ($commentaire->getUserID() === $this) {
                $commentaire->setUserID(null);
            }
        }

        return $this;
    }

    public function getFollows(): Collection
    {
        return $this->follows;
    }

    public function addFollow(Follow $follow): static
    {
        if (!$this->follows->contains($follow)) {
            $this->follows->add($follow);
            $follow->setUserID($this);
        }

        return $this;
    }

    public function removeFollow(Follow $follow): static
    {
        if ($this->follows->removeElement($follow)) {
            if ($follow->getUserID() === $this) {
                $follow->setUserID(null);
            }
        }

        return $this;
    }



    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }
    public function supportsClass(string $class)
    {
        return $class === 'App\Entity\Utilisateur';
    }

    public function getBio(): ?string
    {
        return $this->Bio;
    }

    public function setBio(?string $Bio): static
    {
        $this->Bio = $Bio;

        return $this;
    }

    public function getEcoScore(): ?int
    {
        return $this->EcoScore;
    }

    public function setEcoScore(?int $EcoScore): static
    {
        $this->EcoScore = $EcoScore;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
<script type="module">
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.comment-form').forEach(form => {
        form.addEventListener('submit', function(e) {
            e.preventDefault();

            const formData = new FormData(this);
            const publicationId = formData.get('publicationId');
            const content = formData.get('content');

            fetch('/api/commentaire', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ content: content, publicationId: publicationId })
            })
            .then(response => response.json())
            .then(data => {
                if(data.error) {
                    console.error(data.error);
                } else {
                window.location.reload();
                }
            })
            .catch(error => console.error('Erreur:', error));
        });
    });
document.querySelectorAll('.heart').forEach(btn => {
    btn.addEventListener('click', function() {
        const publicationId = this.getAttribute('data-publication-id');
        const liked = this.getAttribute('data-liked') === 'true';

        fetch(`/like/${publicationId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest' // Si vous utilisez des sessions Symfony
            }
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(data => {
            console.log(data.message);
            // Mettre à jour la couleur de l'icône en fonction de l'état "Like"
            const icon = this.querySelector('ion-icon');
            if (liked) {
                icon.style.color = '#ccc'; // Contour de l'icône
            } else {
                icon.style.color = 'var(--primary-color)'; // Couleur principale (ici utilisée en supposant que la variable CSS --primary-color est définie)
            }
            // Inverser l'état "Like"
            this.setAttribute('data-liked', (!liked).toString());
        })
        .catch(error => {
            console.error('There was an error!', error);
        });
    });
});
});
</script>
{% endblock %}
{% block body %}
<img style="width: 100%" class="wave" src="{{ asset('img/wave.png') }}">

<!-- Affichage des informations de l'utilisateur -->
<div>
{% if app.user and app.user.username != user.username %}
        {% if isFollowedByCurrentUser %}
            <form action="{{ path('unfollow_route', {'username': user.username}) }}" method="POST">
                <button type="submit">Ne plus suivre</button>
            </form>
        {% else %}
            <form action="{{ path('follow_route', {'username': user.username}) }}" method="POST">
                <button type="submit">Suivre</button>
            </form>
        {% endif %}
    {% endif %}

    <div class="profil">
        <div class="imgprofil">
        <a href="{{ path('app_modify_profile') }}">
        <img class="profil-cov" src="{{ asset('/uploads/' ~ user.ProfilePicture) }}" alt="Photo de profile"></a>
        <img class="cover" src="{{ asset('/uploads/' ~ user.ProfileCover) }}" alt="Photo de cover">
</div>

<div class="info">
    <div class="info_stat">   
            <span class="material-symbols-outlined">psychiatry</span>
            <p>ecoScore : {{ user.ecoScore }}</p>
    </div>
    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Publications : {{ nombrePublications }}</p>
    </div>

    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Abonnés : {{ followersCount }}</p>
    </div>

    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Abonnements : {{ followingsCount }}</p>
    </div>
</div>
<div class="bio">
        <div class="bio-i">
            <h2>Profil de l’utilisateur</h2>
            <h1>{{ user.username }}</h1>
            <p>{{ user.Bio }}</p>
            <p>{{ user.email }}</p>
        </div>
        <div class="abone">
            <h2>Abonnés</h2>
            <ul>
                {% for follower in followers %}
                    <li>{{ follower.FollowerID.username }}</li>
                {% endfor %}
            </ul>
            </div>
        <div class="abonnements">
            <h2>Abonnements</h2>
            <ul>
                {% for following in followings %}
                    <li>{{ following.UserID.username }}</li>
                {% endfor %}
            </ul>
        </div>
</div>

<section>
<h2>Publications</h2>
<div class="publication-mosaic">
    {% for data in publicationsData %}
        <div class="publication">
            <div class="publication__header">
            <a href="{{ path('app_profil', {username: data.publication.userID.username}) }}">
            <img src="{{ asset('uploads/' ~ data.publication.userID.profilePicture) }}" alt="Profil de {{ data.publication.userID.username | escape }}" style="height: 35px;"></a>
            <p> {{ data.publication.userID.username | escape }}</p>
            </div>
            <p>{{ data.publication.DateTime|date('Y-m-d H:i') }}</p>
            {% if data.fileType == 'image' %}
                <img src="{{ asset('uploads/' ~ data.publication.postContent) }}" alt="Publication">
            {% elseif data.fileType == 'video' %}
                <video controls src="{{ asset('uploads/' ~ data.publication.postContent) }}"></video>
            {% endif %}
            <div class="publication__likes">
            {% if data.isLikedByCurrentUser %}
                <button onclick="location.href='{{ path('like_publication', {'id': data.publication.id}) }}'" class="heart active">
                    <ion-icon name="leaf"></ion-icon>
                </button>

            {% else %}
                <button onclick="location.href='{{ path('like_publication', {'id': data.publication.id}) }}'" class="heart">
                    <ion-icon name="leaf-outline"></ion-icon>
                </button>
            {% endif %}
            <span>{{ data.likesCount }} likes</span>
            </div>
            <a href="{{ path('app_home', {'id': data.publication.id}) }}">Voir le post</a>

        </div>
    {% else %}
        <p>Cet utilisateur n'a pas encore publié de contenu.</p>
    {% endfor %}
    </div>
</div>

</section>
{% endblock %}