src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateTime = null;



    #[ORM\ManyToOne(inversedBy: 'publications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $UserID = null;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'PostID', cascade: ["remove"])]
    private Collection $commentaires;

    #[ORM\Column(length: 255)]
    private ?string $Post_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Post_content = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'publication')]
    private Collection $likes;


    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostID(): ?int
    {
        return $this->PostID;
    }

    public function setPostID(int $PostID): static
    {
        $this->PostID = $PostID;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): static
    {
        $this->DateTime = $DateTime;

        return $this;
    }


    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }


    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setPostID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPostID() === $this) {
                $commentaire->setPostID(null);
            }
        }

        return $this;
    }

    public function getPostType(): ?string
    {
        return $this->Post_type;
    }

    public function setPostType(string $Post_type): static
    {
        $this->Post_type = $Post_type;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->Post_content;
    }

    public function setPostContent(?string $Post_content): static
    {
        $this->Post_content = $Post_content;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setPublication($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPublication() === $this) {
                $like->setPublication(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this Email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Username = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $Password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfilePicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfileCover = null;

    #[ORM\OneToMany(targetEntity: Connexion::class, mappedBy: 'UserID')]
    private Collection $connexions;

    #[ORM\OneToMany(targetEntity: Publication::class, mappedBy: 'UserID')]
    private Collection $publications;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'UserID')]
    private Collection $commentaires;

    #[ORM\OneToMany(targetEntity: Follow::class, mappedBy: 'UserID')]
    private Collection $follows;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Bio = null;

    #[ORM\Column(nullable: true)]
    private ?int $EcoScore = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'user')]
    private Collection $likes;

    #[ORM\Column(type: 'json')]
    private array $roles = [];
    
    public function __construct()
    {
        $this->connexions = new ArrayCollection();
        $this->publications = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->follows = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->Email; // Ou toute autre propriété qui représente l'identifiant de l'utilisateur
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): static
    {
        $this->Username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): static
    {
        $this->Password = $Password;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->ProfilePicture;
    }

    public function setProfilePicture(?string $ProfilePicture): static
    {
        $this->ProfilePicture = $ProfilePicture;

        return $this;
    }

    public function getProfileCover(): ?string
    {
        return $this->ProfileCover;
    }

    public function setProfileCover(?string $ProfileCover): static
    {
        $this->ProfileCover = $ProfileCover;

        return $this;
    }

    public function getConnexions(): Collection
    {
        return $this->connexions;
    }

    public function addConnexion(Connexion $connexion): static
    {
        if (!$this->connexions->contains($connexion)) {
            $this->connexions->add($connexion);
            $connexion->setUserID($this);
        }

        return $this;
    }

    public function removeConnexion(Connexion $connexion): static
    {
        if ($this->connexions->removeElement($connexion)) {
            if ($connexion->getUserID() === $this) {
                $connexion->setUserID(null);
            }
        }

        return $this;
    }

    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): static
    {
        if (!$this->publications->contains($publication)) {
            $this->publications->add($publication);
            $publication->setUserID($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): static
    {
        if ($this->publications->removeElement($publication)) {
            if ($publication->getUserID() === $this) {
                $publication->setUserID(null);
            }
        }

        return $this;
    }

    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUserID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            if ($commentaire->getUserID() === $this) {
                $commentaire->setUserID(null);
            }
        }

        return $this;
    }

    public function getFollows(): Collection
    {
        return $this->follows;
    }

    public function addFollow(Follow $follow): static
    {
        if (!$this->follows->contains($follow)) {
            $this->follows->add($follow);
            $follow->setUserID($this);
        }

        return $this;
    }

    public function removeFollow(Follow $follow): static
    {
        if ($this->follows->removeElement($follow)) {
            if ($follow->getUserID() === $this) {
                $follow->setUserID(null);
            }
        }

        return $this;
    }



    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }
    public function supportsClass(string $class)
    {
        return $class === 'App\Entity\Utilisateur';
    }

    public function getBio(): ?string
    {
        return $this->Bio;
    }

    public function setBio(?string $Bio): static
    {
        $this->Bio = $Bio;

        return $this;
    }

    public function getEcoScore(): ?int
    {
        return $this->EcoScore;
    }

    public function setEcoScore(?int $EcoScore): static
    {
        $this->EcoScore = $EcoScore;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;



class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username', TextType::class, [
                'label' => false,
                'attr' => ['placeholder' => 'Votre nom d\'utilisateur'],
                'required' => false,
            ])
            ->add('email', EmailType::class, [
                'label' => false,
                'attr' => ['placeholder' => 'Votre adresse email'],
                'required' => false,
            ])
            ->add('bio', TextareaType::class, [
                'label' => false,
                'attr' => ['placeholder' => 'Votre bio'],
                'required' => false,
            ])
            ->add('profilePicture', FileType::class, [
                'label' => 'Photo de profil',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '51200k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Veuillez uploader une image valide',
                    ])
                ],
            ])
            ->add('coverPhoto', FileType::class, [
                'label' => 'Photo de couverture',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '51200k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Veuillez uploader une image valide',
                    ])
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php


namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\UtilisateurType;
use App\Repository\PublicationRepository; // Assurez-vous d'importer le PublicationRepository
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UtilisateurController extends AbstractController
{
    #[Route('/utilisateur', name: 'app_utilisateur')]
    public function profil(PublicationRepository $publicationRepository): Response // Injectez le PublicationRepository
    {
        $utilisateur = $this->getUser();
        
        if (!$utilisateur) {
            return $this->redirectToRoute('app_login');
        }
        
        // Récupérez les publications de l'utilisateur
        $publications = $publicationRepository->findBy(['UserID' => $utilisateur->getId()], ['DateTime' => 'DESC']);
        
        foreach ($publications as $publication) {
            $filename = $publication->getPostContent();
            $extension = pathinfo($filename, PATHINFO_EXTENSION);
            if (in_array(strtolower($extension), ['jpg', 'jpeg', 'png', 'gif'])) {
                $publication->fileType = 'image';
            } elseif (in_array(strtolower($extension), ['mp4', 'avi', 'mov'])) {
                $publication->fileType = 'video';
            } else {
                $publication->fileType = 'unknown';
            }
        }

        $followersCount = $followRepository->countFollowersOfUser($utilisateur);
        $followingsCount = $followRepository->countFollowingsOfUser($utilisateur);
        $followers = $followRepository->findFollowersOfUser($utilisateur);
        $followings = $followRepository->findFollowingsOfUser($utilisateur);

        return $this->render('utilisateur/index.html.twig', [
            'utilisateur' => $utilisateur,
            'publications' => $publications,
            'followersCount' => $followersCount,
            'followingsCount' => $followingsCount,
            'followers' => $followers,
            'followings' => $followings,
        ]);
    }
}

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block javascripts %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.comment-form').forEach(form => {
        form.addEventListener('submit', function(e) {
            e.preventDefault();

            const formData = new FormData(this);
            const publicationId = formData.get('publicationId');
            const content = formData.get('content');

            fetch('/api/commentaire', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ content: content, publicationId: publicationId })
            })
            .then(response => response.json())
            .then(data => {
                if(data.error) {
                    console.error(data.error);
                } else {
                window.location.reload();
                }
            })
            .catch(error => console.error('Erreur:', error));
        });
    });
document.querySelectorAll('.like-btn').forEach(button => {
    button.addEventListener('click', function(e) {
        const publicationId = this.dataset.publicationId;
        fetch(`/like/publication/${publicationId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ like: true }) // Assurez-vous que cela correspond à ce que votre backend attend
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                const likesCountElement = this.previousElementSibling;
                let likesCount = parseInt(likesCountElement.textContent);
                if (this.textContent === 'Like') {
                    likesCountElement.textContent = `${++likesCount} likes`;
                    this.textContent = 'Liked';
                } else {
                    likesCountElement.textContent = `${--likesCount} likes`;
                    this.textContent = 'Like';
                }
            } else {
                alert('Une erreur est survenue.');
            }
        })
        .catch(error => console.error('Erreur:', error));
    });
});


});
</script>
{% endblock %}
{% block body %}
<img class="wave" src="{{ asset('img/wave.png') }}">
<div class="profil">
        <div class="imgprofil">
        <a href="{{ path('app_modify_profile') }}">
        <img class="profil-cov" src="{{ asset('/uploads/' ~ utilisateur.ProfilePicture) }}" alt="Photo de profile">
        </a>
        <img class="cover" src="{{ asset('/uploads/' ~ utilisateur.ProfileCover) }}" alt="Photo de cover">
</div>
<div class="info">
    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Publications : {{ nombrePublications }}</p>
    </div>

    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Abonnés : {{ followersCount }}</p>
    </div>

    <div class="info_stat">   
        <span class="material-symbols-outlined">psychiatry</span>
        <p>Abonnements : {{ followingsCount }}</p>
    </div>
</div>
<div class="bio">
        <div class="bio-i">
            <h2>Profil de l’utilisateur</h2>
            <h1>{{ utilisateur.username }}</h1>
            <p>{{ utilisateur.Bio }}</p>
            <p>{{ utilisateur.email }}</p>
            <a href="{{ path('app_modify_profile') }}">Modifier le profil</a>
        </div>
        <div class="abone">
            <h2>Abonnés</h2>
            <ul>
                {% for follower in followers %}
                    <li>{{ follower.FollowerID.username }}</li>
                {% endfor %}
            </ul>
            </div>
        <div class="abonnements">
            <h2>Abonnements</h2>
            <ul>
                {% for following in followings %}
                    <li>{{ following.UserID.username }}</li>
                {% endfor %}
            </ul>
        </div>
</div>
    <div class="eco-score">
        {% if utilisateur.ecoScore is not null %}
            <p>Votre éco-score est : {{ utilisateur.ecoScore }}</p>
        {% else %}
            <p>Vous n'avez pas encore passé le questionnaire éco-score.</p>
            <a href="{{ path('eco_questionnaire') }}">Passer le questionnaire éco-score</a>
        {% endif %}
    </div>
<h2>Publications</h2>
<div class="publication-mosaic">
    {% for publication in publications %}
        <div class="publication">
            <p>{{ publication.DateTime|date('Y-m-d H:i') }}</p>
            {% if publication.fileType == 'image' %}

                <img src="{{ asset('/uploads/' ~ publication.postContent) }}" alt="Image de publication">

            {% elseif publication.fileType == 'video' %}
                <video controls src="{{ asset('/uploads/' ~ publication.postContent) }}"></video>
            {% endif %}
             <a href="{{ path('publication_edit', {'id': publication.id}) }}" class="btn btn-primary">Modifier</a>
             <a href="{{ path('publication_delete', {'id': publication.id}) }}" class="btn btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette publication ?');">Supprimer</a>
                        <div>
            </div>
        </div>
    {% else %}
        <p>Aucune publication à afficher.</p>
    {% endfor %}
    </div>
</div>
{% endblock %}