src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\Column(type: Types::TEXT)]
    private ?string $Content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateTime = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    private ?Utilisateur $UserID = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Publication $PostID = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentID(): ?int
    {
        return $this->CommentID;
    }

    public function setCommentID(int $CommentID): static
    {
        $this->CommentID = $CommentID;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): static
    {
        $this->Content = $Content;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): static
    {
        $this->DateTime = $DateTime;

        return $this;
    }

    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }

    public function getPostID(): ?Publication
    {
        return $this->PostID;
    }

    public function setPostID(?Publication $PostID): static
    {
        $this->PostID = $PostID;

        return $this;
    }
}

src/Entity/Follow.php
<?php

namespace App\Entity;

use App\Repository\FollowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FollowRepository::class)]
class Follow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'follows')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $UserID = null;

    #[ORM\ManyToOne(inversedBy: 'follows')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $FollowerID = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }

    public function getFollowerID(): ?Utilisateur
    {
        return $this->FollowerID;
    }

    public function setFollowerID(?Utilisateur $FollowerID): static
    {
        $this->FollowerID = $FollowerID;

        return $this;
    }
}

src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateTime = null;



    #[ORM\ManyToOne(inversedBy: 'publications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $UserID = null;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'PostID', cascade: ["remove"])]
    private Collection $commentaires;

    #[ORM\Column(length: 255)]
    private ?string $Post_type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Post_content = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'publication')]
    private Collection $likes;


    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPostID(): ?int
    {
        return $this->PostID;
    }

    public function setPostID(int $PostID): static
    {
        $this->PostID = $PostID;

        return $this;
    }

    public function getDateTime(): ?\DateTimeInterface
    {
        return $this->DateTime;
    }

    public function setDateTime(\DateTimeInterface $DateTime): static
    {
        $this->DateTime = $DateTime;

        return $this;
    }


    public function getUserID(): ?Utilisateur
    {
        return $this->UserID;
    }

    public function setUserID(?Utilisateur $UserID): static
    {
        $this->UserID = $UserID;

        return $this;
    }


    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setPostID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getPostID() === $this) {
                $commentaire->setPostID(null);
            }
        }

        return $this;
    }

    public function getPostType(): ?string
    {
        return $this->Post_type;
    }

    public function setPostType(string $Post_type): static
    {
        $this->Post_type = $Post_type;

        return $this;
    }

    public function getPostContent(): ?string
    {
        return $this->Post_content;
    }

    public function setPostContent(?string $Post_content): static
    {
        $this->Post_content = $Post_content;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setPublication($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPublication() === $this) {
                $like->setPublication(null);
            }
        }

        return $this;
    }

    
}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UtilisateurRepository::class)]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this Email')]
class Utilisateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Username = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $Password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfilePicture = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ProfileCover = null;

    #[ORM\OneToMany(targetEntity: Connexion::class, mappedBy: 'UserID')]
    private Collection $connexions;

    #[ORM\OneToMany(targetEntity: Publication::class, mappedBy: 'UserID')]
    private Collection $publications;


    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'UserID')]
    private Collection $commentaires;

    #[ORM\OneToMany(targetEntity: Follow::class, mappedBy: 'UserID')]
    private Collection $follows;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Bio = null;

    #[ORM\Column(nullable: true)]
    private ?int $EcoScore = null;

    #[ORM\OneToMany(targetEntity: Like::class, mappedBy: 'user')]
    private Collection $likes;

    #[ORM\Column(type: 'json')]
    private array $roles = [];
    
    public function __construct()
    {
        $this->connexions = new ArrayCollection();
        $this->publications = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->follows = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->Email; // Ou toute autre propriété qui représente l'identifiant de l'utilisateur
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): static
    {
        $this->Username = $Username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->Password;
    }

    public function setPassword(string $Password): static
    {
        $this->Password = $Password;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->ProfilePicture;
    }

    public function setProfilePicture(?string $ProfilePicture): static
    {
        $this->ProfilePicture = $ProfilePicture;

        return $this;
    }

    public function getProfileCover(): ?string
    {
        return $this->ProfileCover;
    }

    public function setProfileCover(?string $ProfileCover): static
    {
        $this->ProfileCover = $ProfileCover;

        return $this;
    }

    public function getConnexions(): Collection
    {
        return $this->connexions;
    }

    public function addConnexion(Connexion $connexion): static
    {
        if (!$this->connexions->contains($connexion)) {
            $this->connexions->add($connexion);
            $connexion->setUserID($this);
        }

        return $this;
    }

    public function removeConnexion(Connexion $connexion): static
    {
        if ($this->connexions->removeElement($connexion)) {
            if ($connexion->getUserID() === $this) {
                $connexion->setUserID(null);
            }
        }

        return $this;
    }

    public function getPublications(): Collection
    {
        return $this->publications;
    }

    public function addPublication(Publication $publication): static
    {
        if (!$this->publications->contains($publication)) {
            $this->publications->add($publication);
            $publication->setUserID($this);
        }

        return $this;
    }

    public function removePublication(Publication $publication): static
    {
        if ($this->publications->removeElement($publication)) {
            if ($publication->getUserID() === $this) {
                $publication->setUserID(null);
            }
        }

        return $this;
    }

    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUserID($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            if ($commentaire->getUserID() === $this) {
                $commentaire->setUserID(null);
            }
        }

        return $this;
    }

    public function getFollows(): Collection
    {
        return $this->follows;
    }

    public function addFollow(Follow $follow): static
    {
        if (!$this->follows->contains($follow)) {
            $this->follows->add($follow);
            $follow->setUserID($this);
        }

        return $this;
    }

    public function removeFollow(Follow $follow): static
    {
        if ($this->follows->removeElement($follow)) {
            if ($follow->getUserID() === $this) {
                $follow->setUserID(null);
            }
        }

        return $this;
    }



    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }
    public function supportsClass(string $class)
    {
        return $class === 'App\Entity\Utilisateur';
    }

    public function getBio(): ?string
    {
        return $this->Bio;
    }

    public function setBio(?string $Bio): static
    {
        $this->Bio = $Bio;

        return $this;
    }

    public function getEcoScore(): ?int
    {
        return $this->EcoScore;
    }

    public function setEcoScore(?int $EcoScore): static
    {
        $this->EcoScore = $EcoScore;

        return $this;
    }

    /**
     * @return Collection<int, Like>
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Like $like): static
    {
        if (!$this->likes->contains($like)) {
            $this->likes->add($like);
            $like->setUser($this);
        }

        return $this;
    }

    public function removeLike(Like $like): static
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getUser() === $this) {
                $like->setUser(null);
            }
        }

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);

    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\PublicationRepository;
use App\Repository\UtilisateurRepository;
use App\Repository\LikeRepository;


class SearchController extends AbstractController
{
    private LikeRepository $likeRepository;

    public function __construct( LikeRepository $likeRepository)
    {
        $this->likeRepository = $likeRepository;
    }
    #[Route('/search', name: 'app_search')]
    public function search(Request $request, PublicationRepository $publicationRepo, UtilisateurRepository $userRepo)
    {
        $query = $request->query->get('query');

        if ($query) {
            $publications = $publicationRepo->findByQuery($query);
            $users = $userRepo->findByQuery($query);
        } else {
            $publications = [];
            $users = [];
        }
        $user = $this->getUser();

        $publicationsData = [];

        foreach ($publications as $publication) {
            $publicationId = $publication->getId();
            $isLikedByCurrentUser = $this->likeRepository->isLikedByUser($publicationId, $user);
            $likesCount = $this->likeRepository->countLikesForPublication($publicationId);
            $likers = $this->likeRepository->findLikersByPublication($publicationId); // Assurez-vous d'implémenter cette méthode

            $filename = $publication->getPostContent();
            $extension = pathinfo($filename, PATHINFO_EXTENSION);
            $fileType = 'unknown';
            if (in_array(strtolower($extension), ['jpg', 'jpeg', 'png', 'gif'])) {
                $fileType = 'image';
            } elseif (in_array(strtolower($extension), ['mp4', 'avi', 'mov'])) {
                $fileType = 'video';
            }

            $publicationsData[] = [
                'publication' => $publication,
                'isLikedByCurrentUser' => $isLikedByCurrentUser,
                'likesCount' => $likesCount,
                'fileType' => $fileType,
                'likers' => $likers, // Liste des utilisateurs qui ont liké
            ];
        }

        return $this->render('search/index.html.twig', [
            'publicationsData' => $publicationsData,
            'users' => $users,
            'query' => $query
        ]);
    }
}

templates/search/index.html.twig
{% extends 'base.html.twig' %}
{% block javascripts %}
<script>
document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('.comment-form').forEach(form => {
        form.addEventListener('submit', function(e) {
            e.preventDefault();

            const formData = new FormData(this);
            const publicationId = formData.get('publicationId');
            const content = formData.get('content');

            fetch('/api/commentaire', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ content: content, publicationId: publicationId })
            })
            .then(response => response.json())
            .then(data => {
                if(data.error) {
                    console.error(data.error);
                } else {
                window.location.reload();
                }
            })
            .catch(error => console.error('Erreur:', error));
        });
    });
    document.getElementById('commentForm').addEventListener('submit', function() {
        // Trouvez le bouton de soumission dans le formulaire
        var submitButton = this.querySelector('button[type="submit"]');
        // Désactivez le bouton
        submitButton.disabled = true;
        // Changez le texte du bouton pour informer l'utilisateur
        submitButton.textContent = 'Envoi en cours...';
    });
document.querySelectorAll('.like-btn').forEach(button => {
    button.addEventListener('click', function(e) {
        const publicationId = this.dataset.publicationId;
        fetch(`/like/publication/${publicationId}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ like: true }) // Assurez-vous que cela correspond à ce que votre backend attend
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                const likesCountElement = this.previousElementSibling;
                let likesCount = parseInt(likesCountElement.textContent);
                if (this.textContent === 'Like') {
                    likesCountElement.textContent = `${++likesCount} likes`;
                    this.textContent = 'Liked';
                } else {
                    likesCountElement.textContent = `${--likesCount} likes`;
                    this.textContent = 'Like';
                }
            } else {
                alert('Une erreur est survenue.');
            }
        })
        .catch(error => console.error('Erreur:', error));
    });
});


});
</script>
{% endblock %}
{% block body %}
<img style="width: 100%" class="wave" src="{{ asset('img/wave.png') }}">
<div class="publications">
    {% for data in publicationsData %}
        <div class="publication">
            <div class="publication__header">
                <div class="publication__author">
                    <a href="{{ path('app_profil', {username: data.publication.userID.username}) }}">
                    <img src="{{ asset('uploads/' ~ data.publication.userID.profilePicture) }}" alt="Profil de {{ data.publication.userID.username | escape }}" style="width: 40px;"></a>
                    <p> {{ data.publication.userID.username | escape }}</p>
                </div>
                <p>{{ data.publication.dateTime|date('Y-m-d H:i') }}</p>
            </div>
            <div class="publication__content">
            {% if data.fileType == 'image' %}
                <img src="{{ asset('uploads/' ~ data.publication.postContent) }}" alt="Publication">
            {% elseif data.fileType == 'video' %}
                <video controls src="{{ asset('uploads/' ~ data.publication.postContent) }}"></video>
            {% endif %}
            </div>
            <div class="publication__likes">
            {% if data.isLikedByCurrentUser %}
            <button onclick="location.href='{{ path('like_publication', {'id': data.publication.id}) }}'">DisLike</button>
            {% else %}
            <button onclick="location.href='{{ path('like_publication', {'id': data.publication.id}) }}'">Like</button>
            {% endif %}
            
            <span>{{ data.likesCount }} likes</span>
             {% if data.likers|length > 0 %}
            <p>Liked by:</p>
            <ul>
            {% for liker in data.likers %}
                    <img src="{{ asset('uploads/' ~ liker.ProfilePicture) }}" alt="profil" style="width: 25px;">
                    <li>{{ liker.Username }}</li>
                
            {% endfor %}
            </ul>
            {% endif %}
            </div>
            <p>{{ data.publication.postType | escape }}</p>

            <div class="publication__comments">
                {% for commentaire in data.publication.commentaires %}
                    <div class="comment">
                        <img src="{{ asset('uploads/' ~ commentaire.userID.profilePicture) }}" alt="Profil de {{ commentaire.userID.username | escape }}" style="width: 25px;">
                        <p><strong>{{ commentaire.userID.username | escape }}</strong>: {{ commentaire.content | escape }} </p>
                        <p class="comment__date">{{ commentaire.dateTime|date('Y-m-d H:i') }}</p>
                    </div>
                {% endfor %}
            </div>

            <form id="commentForm" class="comment-form" data-publication-id="{{ data.publication.id }}" action="" method="post">
                <input type="text" name="content" placeholder="Ajoutez un commentaire..." required>
                <input type="hidden" name="publicationId" value="{{ data.publication.id }}">
                <button type="submit">Commenter</button>
            </form>
        </div>
</div>

<section>
  <div class="skewed"></div>

    {% else %}
        <p>Aucune Publication trouvée.</p>
    {% endfor %}
</div>

    <div class="searchprofil">
    <h2>Profils</h2>
    {% for user in users %}
        <div>{{ user.username }}: {{ user.email }}</div>
    {% else %}
        <p>Aucun profil trouvé.</p>
    {% endfor %}
    </div>
</section>

    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

{% endblock %}